/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    docs: [
        {
            type: 'doc',
            id: 'introduction',
            label: 'Introduction'
        },
        {
            type: 'category',
            label: 'Data Marketplace',
            items: ['data-marketplace/overview',
                'data-marketplace/architecture',
                'data-marketplace/deployment-and-testing.md',]

        },
        {
            type: 'category',
            label: 'Document Immutability',
            items: ['doc-immutability/overview',
                'doc-immutability/architecture',]
        },
        {
            type: 'category',
            label: 'P2P Energy Grid',
            items: ['p2p-energy/overview',
                'p2p-energy/architecture',
                'p2p-energy/deployment-and-testing',]
        },
        {
            type: 'category',
            label: 'Tangle Data Storage',
            items: ['tangle-data-storage/overview',
                'tangle-data-storage/architecture',
                'tangle-data-storage/deployment-and-testing',]
        },
        {
            type: 'category',
            label: 'Track And Trace',
            items: ['track-and-trace/overview',
                'track-and-trace/architecture',
                'track-and-trace/deployment-and-testing',
                {
                    type: 'link',
                    href: 'https://iotaledger.github.io/gtsc-track-trace/tutorial/track-trace-ledger-api-tutorial-101',
                    label: 'Track And Trace/REST API 101 Tutorial'
                }]
        },
    ],
};
